id: 3c7550dc94b141fb93ab4ab2f4ed3278
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_186-The_Teaching_on_the_Extraordinary_Transformation-v2
  language: bo
  author: ''
  volume: {}
